### ISSUE TITLE
Enable Doc in windows actions

### ISSUE THREAD

**Issue by DorianGerardin** [OpenFLUID/openfluid#1288]
```yml
- name: Installation of pandoc
  uses: r-lib/actions/setup-pandoc@v2
      
- name: Installation of latex
  uses: teatimeguest/setup-texlive-action@v3
    with:
      packages: |
        scheme-full
        bibtex
...
- name: Configuration
  run: cmake .. -G "MSYS Makefiles"
```
